name: Build and Publish SDK

on:
  pull_request:
    branches:
      - sdk-development
  push:
    branches:
      - sdk-development

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./weblock-wallet/pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Generate .npmrc
        working-directory: ./weblock-wallet
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@wefunding-dev:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Install dependencies
        working-directory: ./weblock-wallet
        run: pnpm install

      - name: Build packages
        working-directory: ./weblock-wallet
        run: pnpm -r run build

      - name: Increment version
        if: ${{ github.event_name == 'push' }}
        working-directory: ./weblock-wallet
        run: pnpm version patch

      - name: Update dependencies
        if: ${{ github.event_name == 'push' }}
        working-directory: ./weblock-wallet
        run: node scripts/update-dependencies.js

      - name: Publish packages
        if: ${{ github.event_name == 'push' }}
        working-directory: ./weblock-wallet
        run: pnpm -r publish --access restricted --no-git-checks

      - name: Revert dependencies to workspace
        if: ${{ github.event_name == 'push' }}
        working-directory: ./weblock-wallet
        run: node scripts/revert-dependencies.js

      - name: Push changes and tags
        if: ${{ github.event_name == 'push' }}
        working-directory: ./weblock-wallet
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "chore: bump version and revert dependencies" || echo "No changes to commit"
          git push origin sdk-development
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
