name: Build and Publish SDK

on:
  pull_request:
    branches:
      - sdk-development

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js with pnpm cache
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm # Use pnpm for caching
          cache-dependency-path: ./weblock-wallet/pnpm-lock.yaml # Specify lock file path

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Change to workspace directory and install dependencies
      - name: Install dependencies
        working-directory: ./weblock-wallet
        run: pnpm install

      # Step 5: Run build script
      - name: Build packages
        working-directory: ./weblock-wallet
        run: pnpm -r run build

      # Step 6: Run the custom script to update dependencies
      - name: Update dependencies
        working-directory: ./weblock-wallet
        run: node scripts/update-dependencies.js

      # Step 7: Publish packages
      - name: Publish packages
        working-directory: ./weblock-wallet
        run: pnpm -r publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
